name: flutter_shop_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  lottie: ^1.2.2
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0

  get: ^4.6.1
  firebase_core: ^1.13.0
  firebase_auth: ^3.3.8
  super_repository:
    git:
      url: http://github.com/abdullahAlwajih/Super-Repository.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/core/assets/images/
    - lib/core/assets/lotties/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
